package setup

import (
	"fmt"
	"io"
	"math/big"
	"strings"
	"text/template"

	"github.com/consensys/gnark-crypto/ecc/bn254"
	"github.com/consensys/gnark-crypto/ecc/bn254/fp"
	"github.com/consensys/gnark-crypto/ecc/bn254/fr"
	"github.com/consensys/gnark/backend/groth16"
	groth16bn254 "github.com/consensys/gnark/backend/groth16/bn254"
	"github.com/consensys/gnark/backend/plonk"
	plonkbn254 "github.com/consensys/gnark/backend/plonk/bn254"
)

// ─── Groth16 VK Export ──────────────────────────────────────────────────────

// groth16VKData holds template data for Groth16 VK Solidity library generation.
type groth16VKData struct {
	LibraryName string
	NumInputs   int

	AlphaX, AlphaY string

	BetaNegX1, BetaNegX0, BetaNegY1, BetaNegY0 string
	GammaNegX1, GammaNegX0, GammaNegY1, GammaNegY0 string
	DeltaNegX1, DeltaNegX0, DeltaNegY1, DeltaNegY0 string

	IC []g1Point // IC[0] = constant, IC[1..n] = public input coefficients
}

type g1Point struct {
	X, Y string
}

// ExportGroth16VKSolidity writes a Solidity library containing only the verification key
// constants for a Groth16 circuit, formatted for the Groth16 precompile interface.
func ExportGroth16VKSolidity(vk groth16.VerifyingKey, w io.Writer, circuitName string) error {
	concreteVK, ok := vk.(*groth16bn254.VerifyingKey)
	if !ok {
		return fmt.Errorf("expected BN254 Groth16 verifying key, got %T", vk)
	}

	// Negate Beta, Gamma, Delta G2 points (precompile expects negated form)
	var negBeta, negGamma, negDelta bn254.G2Affine
	negBeta.Neg(&concreteVK.G2.Beta)
	negGamma.Neg(&concreteVK.G2.Gamma)
	negDelta.Neg(&concreteVK.G2.Delta)

	numInputs := len(concreteVK.G1.K) - 1 // K[0] is constant, K[1..n] are public inputs

	data := groth16VKData{
		LibraryName: pascalCase(circuitName) + "VK",
		NumInputs:   numInputs,

		AlphaX: fpStr(&concreteVK.G1.Alpha.X),
		AlphaY: fpStr(&concreteVK.G1.Alpha.Y),

		// EIP-197 order: [X.A1, X.A0, Y.A1, Y.A0] (imaginary first)
		BetaNegX1: fpStr(&negBeta.X.A1), BetaNegX0: fpStr(&negBeta.X.A0),
		BetaNegY1: fpStr(&negBeta.Y.A1), BetaNegY0: fpStr(&negBeta.Y.A0),
		GammaNegX1: fpStr(&negGamma.X.A1), GammaNegX0: fpStr(&negGamma.X.A0),
		GammaNegY1: fpStr(&negGamma.Y.A1), GammaNegY0: fpStr(&negGamma.Y.A0),
		DeltaNegX1: fpStr(&negDelta.X.A1), DeltaNegX0: fpStr(&negDelta.X.A0),
		DeltaNegY1: fpStr(&negDelta.Y.A1), DeltaNegY0: fpStr(&negDelta.Y.A0),
	}

	for _, k := range concreteVK.G1.K {
		data.IC = append(data.IC, g1Point{
			X: fpStr(&k.X),
			Y: fpStr(&k.Y),
		})
	}

	return groth16VKTemplate.Execute(w, data)
}

var groth16VKTemplate = template.Must(template.New("groth16vk").Parse(`// SPDX-License-Identifier: MIT
// Auto-generated by muri-zkproof — DO NOT EDIT
pragma solidity ^0.8.13;

/// @notice Groth16 verification key constants for the precompile at
///         0x0300000000000000000000000000000000000001.
///         G2 points use EIP-197 ordering [x1, x0, y1, y0].
library {{.LibraryName}} {
    uint256 internal constant NUM_INPUTS = {{.NumInputs}};

    // ── Alpha G1 ────────────────────────────────────────────────────
    uint256 internal constant ALPHA_X = {{.AlphaX}};
    uint256 internal constant ALPHA_Y = {{.AlphaY}};

    // ── Negated Beta G2 [x1, x0, y1, y0] ───────────────────────────
    uint256 internal constant BETA_NEG_X1 = {{.BetaNegX1}};
    uint256 internal constant BETA_NEG_X0 = {{.BetaNegX0}};
    uint256 internal constant BETA_NEG_Y1 = {{.BetaNegY1}};
    uint256 internal constant BETA_NEG_Y0 = {{.BetaNegY0}};

    // ── Negated Gamma G2 [x1, x0, y1, y0] ──────────────────────────
    uint256 internal constant GAMMA_NEG_X1 = {{.GammaNegX1}};
    uint256 internal constant GAMMA_NEG_X0 = {{.GammaNegX0}};
    uint256 internal constant GAMMA_NEG_Y1 = {{.GammaNegY1}};
    uint256 internal constant GAMMA_NEG_Y0 = {{.GammaNegY0}};

    // ── Negated Delta G2 [x1, x0, y1, y0] ──────────────────────────
    uint256 internal constant DELTA_NEG_X1 = {{.DeltaNegX1}};
    uint256 internal constant DELTA_NEG_X0 = {{.DeltaNegX0}};
    uint256 internal constant DELTA_NEG_Y1 = {{.DeltaNegY1}};
    uint256 internal constant DELTA_NEG_Y0 = {{.DeltaNegY0}};

    // ── IC points (length = NUM_INPUTS + 1) ─────────────────────────
{{- range $i, $pt := .IC}}
    uint256 internal constant IC_{{$i}}_X = {{$pt.X}};
    uint256 internal constant IC_{{$i}}_Y = {{$pt.Y}};
{{- end}}
}
`))

// ─── PLONK VK Export ────────────────────────────────────────────────────────

// plonkVKData holds template data for PLONK VK Solidity library generation.
type plonkVKData struct {
	LibraryName    string
	DomainSize     uint64
	NbPublicInputs uint64
	Omega          string
	CosetShift     string

	QL, QR, QM, QO, QK g1Point
	S1, S2, S3          g1Point

	// G2 SRS points in EIP-197 order [x1, x0, y1, y0]
	G2Srs0X1, G2Srs0X0, G2Srs0Y1, G2Srs0Y0 string
	G2Srs1X1, G2Srs1X0, G2Srs1Y1, G2Srs1Y0 string
}

// ExportPlonkVKSolidity writes a Solidity library containing only the verification key
// constants for a PLONK circuit, formatted for the PLONK precompile interface.
func ExportPlonkVKSolidity(vk plonk.VerifyingKey, w io.Writer, circuitName string) error {
	concreteVK, ok := vk.(*plonkbn254.VerifyingKey)
	if !ok {
		return fmt.Errorf("expected BN254 PLONK verifying key, got %T", vk)
	}

	data := plonkVKData{
		LibraryName:    pascalCase(circuitName) + "VK",
		DomainSize:     concreteVK.Size,
		NbPublicInputs: concreteVK.NbPublicVariables,
		Omega:          frStr(&concreteVK.Generator),
		CosetShift:     frStr(&concreteVK.CosetShift),

		QL: g1Point{X: fpStr(&concreteVK.Ql.X), Y: fpStr(&concreteVK.Ql.Y)},
		QR: g1Point{X: fpStr(&concreteVK.Qr.X), Y: fpStr(&concreteVK.Qr.Y)},
		QM: g1Point{X: fpStr(&concreteVK.Qm.X), Y: fpStr(&concreteVK.Qm.Y)},
		QO: g1Point{X: fpStr(&concreteVK.Qo.X), Y: fpStr(&concreteVK.Qo.Y)},
		QK: g1Point{X: fpStr(&concreteVK.Qk.X), Y: fpStr(&concreteVK.Qk.Y)},

		S1: g1Point{X: fpStr(&concreteVK.S[0].X), Y: fpStr(&concreteVK.S[0].Y)},
		S2: g1Point{X: fpStr(&concreteVK.S[1].X), Y: fpStr(&concreteVK.S[1].Y)},
		S3: g1Point{X: fpStr(&concreteVK.S[2].X), Y: fpStr(&concreteVK.S[2].Y)},

		// EIP-197 order: [A1, A0, A1, A0] (imaginary first)
		G2Srs0X1: fpStr(&concreteVK.Kzg.G2[0].X.A1), G2Srs0X0: fpStr(&concreteVK.Kzg.G2[0].X.A0),
		G2Srs0Y1: fpStr(&concreteVK.Kzg.G2[0].Y.A1), G2Srs0Y0: fpStr(&concreteVK.Kzg.G2[0].Y.A0),
		G2Srs1X1: fpStr(&concreteVK.Kzg.G2[1].X.A1), G2Srs1X0: fpStr(&concreteVK.Kzg.G2[1].X.A0),
		G2Srs1Y1: fpStr(&concreteVK.Kzg.G2[1].Y.A1), G2Srs1Y0: fpStr(&concreteVK.Kzg.G2[1].Y.A0),
	}

	return plonkVKTemplate.Execute(w, data)
}

var plonkVKTemplate = template.Must(template.New("plonkvk").Parse(`// SPDX-License-Identifier: MIT
// Auto-generated by muri-zkproof — DO NOT EDIT
pragma solidity ^0.8.13;

/// @notice PLONK verification key constants for the precompile at
///         0x0300000000000000000000000000000000000004.
///         G2 points use EIP-197 ordering [x1, x0, y1, y0].
library {{.LibraryName}} {
    uint64 internal constant DOMAIN_SIZE = {{.DomainSize}};
    uint64 internal constant NB_PUBLIC_INPUTS = {{.NbPublicInputs}};
    uint256 internal constant OMEGA = {{.Omega}};

    // ── Gate selector commitments (G1) ──────────────────────────────
    uint256 internal constant QL_X = {{.QL.X}};
    uint256 internal constant QL_Y = {{.QL.Y}};
    uint256 internal constant QR_X = {{.QR.X}};
    uint256 internal constant QR_Y = {{.QR.Y}};
    uint256 internal constant QM_X = {{.QM.X}};
    uint256 internal constant QM_Y = {{.QM.Y}};
    uint256 internal constant QO_X = {{.QO.X}};
    uint256 internal constant QO_Y = {{.QO.Y}};
    uint256 internal constant QK_X = {{.QK.X}};
    uint256 internal constant QK_Y = {{.QK.Y}};

    // ── Permutation commitments (G1) ────────────────────────────────
    uint256 internal constant S1_X = {{.S1.X}};
    uint256 internal constant S1_Y = {{.S1.Y}};
    uint256 internal constant S2_X = {{.S2.X}};
    uint256 internal constant S2_Y = {{.S2.Y}};
    uint256 internal constant S3_X = {{.S3.X}};
    uint256 internal constant S3_Y = {{.S3.Y}};

    // ── G2 SRS point 0 [x1, x0, y1, y0] ────────────────────────────
    uint256 internal constant G2_SRS_0_X1 = {{.G2Srs0X1}};
    uint256 internal constant G2_SRS_0_X0 = {{.G2Srs0X0}};
    uint256 internal constant G2_SRS_0_Y1 = {{.G2Srs0Y1}};
    uint256 internal constant G2_SRS_0_Y0 = {{.G2Srs0Y0}};

    // ── G2 SRS point 1 [x1, x0, y1, y0] ────────────────────────────
    uint256 internal constant G2_SRS_1_X1 = {{.G2Srs1X1}};
    uint256 internal constant G2_SRS_1_X0 = {{.G2Srs1X0}};
    uint256 internal constant G2_SRS_1_Y1 = {{.G2Srs1Y1}};
    uint256 internal constant G2_SRS_1_Y0 = {{.G2Srs1Y0}};

    // ── Coset shift ─────────────────────────────────────────────────
    uint256 internal constant COSET_SHIFT = {{.CosetShift}};
}
`))

// ─── Helpers ────────────────────────────────────────────────────────────────

// fpStr converts an fp.Element (base field) to its decimal string representation.
func fpStr(e *fp.Element) string {
	var b big.Int
	e.BigInt(&b)
	return b.String()
}

// frStr converts an fr.Element (scalar field) to its decimal string representation.
func frStr(e *fr.Element) string {
	var b big.Int
	e.BigInt(&b)
	return b.String()
}

// pascalCase converts a lowercase circuit name to PascalCase.
// "poi" → "Poi", "keyleak" → "Keyleak", "archive_poi" → "ArchivePoi"
func pascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}
